name: BigTransit Deployment Pipeline
on:
  push:
    branches:
    - main
jobs:
  Commit:
    name: Commit stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v3          
      - name: Install NPM Dependencies
        run: npm install
      - name: Install SST ION deployment CLI
        run: brew install sst/tap/sst
      - name: Check SST version
        run: sst version
      - name: Run TypeScript Build
        run: npm run build
      - name: Check for types.d.ts file
        run: |
          if [ -f "types.d.ts" ]; then
            echo "types.d.ts file exists."
          else
            echo "types.d.ts file does not exist."
            exit 1
          fi                
