name: BigTransit Deployment Pipeline
on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  Commit:
    name: Commit stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'

      - uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Run NPM Audit
        run: node scripts/check-audit.js    

      - name: Install SST ION deployment CLI
        run: curl -fsSL https://sst.dev/install | bash

      - name: Check SST version
        run: sst version

      - name: Force SST ION CLI to version 3.17.0
        run: sst upgrade 3.17.0

      - name: Check SST version
        run: sst version

      - name: Install SST AWS provider
        run: sst install

      - name: Run TypeScript build
        run: npm run build

      - name: Run Unit Tests
        run: npm run unit
      - name: Run Frontend Unit Tests
        run: |
          cd examples/frontend
          npm install
          npm test

      - name: Archive node_modules and .sst
        run: tar -czf artifacts.tar.gz node_modules .sst

      - name: Upload Commit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node_modules_and_sst
          path: artifacts.tar.gz
  Acceptance:
    needs: Commit
    name: Functional acceptance test stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::710285992829:role/GitHubActionsSSTdeploy
          aws-region: eu-west-2             

      - name: Download Commit artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules_and_sst
          path: .
      
      - name: Extract artifacts
        run: tar -xzf artifacts.tar.gz

      - name: Install SST ION deployment CLI
        run: curl -fsSL https://sst.dev/install | bash

      - name: Check SST version
        run: sst version

      - name: Force SST ION CLI to version 3.17.0
        run: sst upgrade 3.17.0

      - name: Check SST version
        run: sst version

      - name: Install SST AWS provider
        run: sst install

      - name: Deploy to AWS Acceptance environment
        run: node scripts/deploy-acceptance.js

      - name: Run Functional Acceptance Tests
        run: npm run acceptance

      - name: Tear down and remove AWS Acceptance environment
        if: success()
        run: sst remove --stage acceptance