name: BigTransit Deployment Pipeline
on:
  push:
    branches:
    - main
jobs:
  Commit:
    name: Commit stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v4          
      - name: Install NPM Dependencies
        run: npm install
      - name: Install SST ION deployment CLI
        run: brew install sst/tap/sst
      - name: Check SST Version
        run: sst version
      - name: Run TypeScript Build
        run: npm run build
      - name: Run Unit Tests
        run: npm run unit
  Acceptance:
    needs: Commit
    name: Functional acceptance test stage
    runs-on: macos-13
    steps:
      - name: Deploy to AWS acceptance environment
        run: sst deploy

