name: BigTransit Deployment Pipeline
on:
  push:
    branches:
    - main
jobs:
  Commit:
    name: Commit stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v3          
      - name: Install Dependencies
        run: npm install
      - name: Run TypeScript Build
        run: npm run build        
