name: BigTransit Deployment Pipeline
on:
  push:
    branches:
    - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  Commit:
    name: Commit stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v4          
      - name: Install NPM Dependencies
        run: npm install
      - name: Install SST ION deployment CLI
        run: brew install sst/tap/sst
      - name: Check SST Version
        run: sst version
      - name: Install SST AWS provider
        run: sst install           
      - name: Run TypeScript Build
        run: npm run build
      - name: Run Unit Tests
        run: npm run unit
        
      - name: Archive node_modules and .sst
        run: tar -czf artifacts.tar.gz node_modules .sst
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: node_modules_and_sst
          path: artifacts.tar.gz
  Acceptance:
    needs: Commit
    name: Functional acceptance test stage
    runs-on: macos-13
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::710285992829:role/GitHubActionsSSTdeploy
          aws-region: eu-west-2             
      - name: Install NPM Dependencies
        run: npm install
      - name: Install SST ION deployment CLI
        run: brew install sst/tap/sst
      - name: Check SST Version
        run: sst version
      - name: Install SST AWS provider
        run: sst install        
      - name: Deploy to AWS acceptance environment
        run: sst deploy --stage production

